[app]
name = "ekube"
encrypt_key = "PkOTnIlowNs4ioPZ8VODAZYSeOrMCshM"

[app.http]
host = "127.0.0.1"
port = "8081"

[app.grpc]
host = "0.0.0.0"
port = "18081"

[mongodb]
endpoints = ["10.31.0.200:27017"]
username = "ekube"
password = "123456"
database = "ekube"

[etcd]
endpoints = ["10.31.0.200:2381"]
username = "ekube"
password = "123456"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"
