/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	v1 "ekube/api/k8s/users/v1"
	scheme "ekube/pkg/client/clientset/versioned/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// UsersesGetter has a method to return a UsersInterface.
// A group's client should implement this interface.
type UsersesGetter interface {
	Userses() UsersInterface
}

// UsersInterface has methods to work with Users resources.
type UsersInterface interface {
	Create(ctx context.Context, users *v1.Users, opts metav1.CreateOptions) (*v1.Users, error)
	Update(ctx context.Context, users *v1.Users, opts metav1.UpdateOptions) (*v1.Users, error)
	UpdateStatus(ctx context.Context, users *v1.Users, opts metav1.UpdateOptions) (*v1.Users, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Users, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.UsersList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Users, err error)
	UsersExpansion
}

// userses implements UsersInterface
type userses struct {
	client rest.Interface
}

// newUserses returns a Userses
func newUserses(c *UsersV1Client) *userses {
	return &userses{
		client: c.RESTClient(),
	}
}

// Get takes name of the users, and returns the corresponding users object, and an error if there is any.
func (c *userses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Users, err error) {
	result = &v1.Users{}
	err = c.client.Get().
		Resource("userses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Userses that match those selectors.
func (c *userses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.UsersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.UsersList{}
	err = c.client.Get().
		Resource("userses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested userses.
func (c *userses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("userses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a users and creates it.  Returns the server's representation of the users, and an error, if there is any.
func (c *userses) Create(ctx context.Context, users *v1.Users, opts metav1.CreateOptions) (result *v1.Users, err error) {
	result = &v1.Users{}
	err = c.client.Post().
		Resource("userses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(users).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a users and updates it. Returns the server's representation of the users, and an error, if there is any.
func (c *userses) Update(ctx context.Context, users *v1.Users, opts metav1.UpdateOptions) (result *v1.Users, err error) {
	result = &v1.Users{}
	err = c.client.Put().
		Resource("userses").
		Name(users.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(users).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *userses) UpdateStatus(ctx context.Context, users *v1.Users, opts metav1.UpdateOptions) (result *v1.Users, err error) {
	result = &v1.Users{}
	err = c.client.Put().
		Resource("userses").
		Name(users.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(users).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the users and deletes it. Returns an error if one occurs.
func (c *userses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("userses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *userses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("userses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched users.
func (c *userses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Users, err error) {
	result = &v1.Users{}
	err = c.client.Patch(pt).
		Resource("userses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
